"""
OFFICE FINALISE - Makes a Word or PowerPoint file safe to submit.

Two problems this fixes, both invisible on the page:

1. Language. python-docx and python-pptx start from templates tagged
   American English (en-US). Word then spell-checks the work in the wrong
   language ('analyse' wrong in British work, every word wrong in Spanish).
   Every language tag is set to the work language (LANG, set by layout.py:
   en-GB, en-US, es-ES, pt-PT, it-IT, de-DE or ro-RO).

2. File properties. The same templates carry author 'python-docx', last
   modified by the library's author, 2013 dates and the comment
   'generated by python-docx'. And a document the student writes in Word
   carries their name as author, which breaks anonymous marking even when
   the page itself is clean. The properties are rewritten: author
   and last-modified-by become the Student ID, the title and subject are
   the document's own, the dates are now, the comment is empty.

Also reports comments and tracked changes left in a Word document: they
carry the author's name and must not be submitted.

Only the file's packaging is changed, never a word of its content.
"""
import os
import re
import shutil
import tempfile
import zipfile
from datetime import datetime, timezone
from xml.sax.saxutils import escape

LANG = "en-GB"                      # layout.apply() sets the work language

_W_LANG = re.compile(r"(<w:lang\b[^>]*?\bw:val=\")([^\"]*)(\")")
_W_THEME_LANG = re.compile(r"(<w:themeFontLang\b[^>]*?\bw:val=\")([^\"]*)(\")")
_A_LANG = re.compile(r"(<a:(?:rPr|endParaRPr|defRPr)\b[^>]*?\blang=\")([^\"]*)(\")")
_RPR_DEFAULT = re.compile(r"(<w:rPrDefault>\s*<w:rPr>)(.*?)(</w:rPr>)", re.S)

CORE_TEMPLATE = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
    '<cp:coreProperties '
    'xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
    'xmlns:dc="http://purl.org/dc/elements/1.1/" '
    'xmlns:dcterms="http://purl.org/dc/terms/" '
    'xmlns:dcmitype="http://purl.org/dc/dcmitype/" '
    'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
    '<dc:title>{title}</dc:title>'
    '<dc:subject>{subject}</dc:subject>'
    '<dc:creator>{author}</dc:creator>'
    '<cp:keywords></cp:keywords>'
    '<dc:description></dc:description>'
    '<dc:language>{lang}</dc:language>'
    '<cp:lastModifiedBy>{author}</cp:lastModifiedBy>'
    '<cp:revision>1</cp:revision>'
    '<dcterms:created xsi:type="dcterms:W3CDTF">{now}</dcterms:created>'
    '<dcterms:modified xsi:type="dcterms:W3CDTF">{now}</dcterms:modified>'
    '</cp:coreProperties>')


def _tag(xml, name):
    m = re.search(r"<[\w:]*%s\b[^>]*>([^<]*)</" % name, xml)
    return m.group(1).strip() if m else ""


def read_properties(path):
    """The file properties a marker could see: author, last editor, title."""
    try:
        with zipfile.ZipFile(path) as z:
            core = z.read("docProps/core.xml").decode("utf-8", "replace")
    except (KeyError, zipfile.BadZipFile, OSError):
        return {}
    return {k: _tag(core, k) for k in
            ("creator", "lastModifiedBy", "title", "subject", "description",
             "keywords")}


def review_marks(path):
    """Comments and tracked changes in a .docx: (count, set of author names)."""
    count, authors = 0, set()
    try:
        with zipfile.ZipFile(path) as z:
            names = z.namelist()
            parts = [n for n in names if n.startswith("word/") and n.endswith(".xml")]
            for n in parts:
                x = z.read(n).decode("utf-8", "replace")
                if n == "word/comments.xml":
                    found = re.findall(r"<w:comment\b[^>]*>", x)
                elif n.startswith(("word/document", "word/header", "word/footer",
                                   "word/footnotes", "word/endnotes")):
                    found = re.findall(r"<w:(?:ins|del|moveFrom|moveTo)\b[^>]*>", x)
                else:
                    continue
                count += len(found)
                for tag in found:
                    a = re.search(r'w:author="([^"]*)"', tag)
                    if a and a.group(1).strip():
                        authors.add(a.group(1).strip())
    except (zipfile.BadZipFile, OSError):
        pass
    return count, authors


def languages(path):
    """How many text runs carry each language tag."""
    counts = {}
    try:
        with zipfile.ZipFile(path) as z:
            for n in z.namelist():
                if n.endswith(".xml") and n.startswith(("word/", "ppt/")):
                    x = z.read(n).decode("utf-8", "replace")
                    for rx in (_W_LANG, _A_LANG):
                        for m in rx.finditer(x):
                            counts[m.group(2)] = counts.get(m.group(2), 0) + 1
    except (zipfile.BadZipFile, OSError):
        pass
    return counts


def finalise(path, author="", title="", subject=""):
    """Rewrite language tags and file properties in place.

    Returns {"languages_before": {...}, "properties_before": {...}}.
    """
    from .workspace import refuse_cloud_save
    refuse_cloud_save(path, "the file")
    report = {"languages_before": languages(path),
              "properties_before": read_properties(path)}
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    core = CORE_TEMPLATE.format(title=escape(title or ""),
                                subject=escape(subject or ""),
                                author=escape(author or ""), lang=LANG, now=now)

    fd, tmp = tempfile.mkstemp(suffix=os.path.splitext(path)[1],
                               dir=os.path.dirname(os.path.abspath(path)))
    os.close(fd)
    try:
        with zipfile.ZipFile(path) as src, \
                zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as dst:
            for item in src.infolist():
                data = src.read(item.filename)
                name = item.filename
                if name == "docProps/core.xml":
                    data = core.encode("utf-8")
                elif name.endswith(".xml") and name.startswith(("word/", "ppt/")):
                    x = data.decode("utf-8")
                    x = _W_LANG.sub(lambda m: m.group(1) + LANG + m.group(3), x)
                    x = _W_THEME_LANG.sub(lambda m: m.group(1) + LANG + m.group(3), x)
                    x = _A_LANG.sub(lambda m: m.group(1) + LANG + m.group(3), x)
                    if name == "word/styles.xml":
                        x = _ensure_default_language(x)
                    data = x.encode("utf-8")
                dst.writestr(item, data)
        shutil.move(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.remove(tmp)
    return report


def _ensure_default_language(styles_xml):
    """Give the document the work language as its default if it has none."""
    m = _RPR_DEFAULT.search(styles_xml)
    if m and "<w:lang" not in m.group(2):
        return (styles_xml[:m.end(2)] + '<w:lang w:val="%s"/>' % LANG
                + styles_xml[m.end(2):])
    return styles_xml
