"""The hidden about: pages explained page by page: both tracks in English (public), plain words in Romanian (private),
rendered from one source and checked.

    fieldkit build-harness hidden-pages-doc <task>            check the source and the published copies
    fieldkit build-harness hidden-pages-doc <task> write=1    render them, then check

Born 2026-10-08 (D-157-40). The maintainer found about:fingerprintingprotection, a page about:about does not list,
and asked for every hidden page to be mapped, pictured and explained "in layman terms ... both in romanian and in
english", the English published with a picture of each page, and for every tool made on the way to stay in the
harness. When upstream adds a hidden page, the register check (decision D-157-40, about_register) stops the build
until the page is reviewed; this check then fails until the page is explained here as well.

Source, in the owner repo (private):
  docs/hidden-pages/pages/*.yaml    {pages: [{name, shots, no_shot, en: {title, layman, developer},
                                               ro: {title, network, layman}}]}
  docs/hidden-pages/intro.yaml      {order: [names], en: {title, intro, method}, ro: {title, intro}}
  docs/hidden-pages/shots/          the pictures (probe about-pages shots=, probe error-pages)
  docs/hidden-pages/research/       the source reading every fact comes from
  decisions/ABOUT-PAGES.yaml        verdict, decision and network per page (never typed twice)
Out:
  public   <patch-set repo>/docs/HIDDEN-PAGES.md, <patch-set repo>/docs/screenshots/hidden-pages/*.png
  private  docs/hidden-pages/HIDDEN-PAGES.ro.md
Checks (fail closed):
  - every page the register says is or was hidden is explained, nothing else is, and `order` names each once;
  - every entry has all its texts; every picture it names exists; a page without a picture says why;
  - the English is checked as a release document (gdocs.releasedocs, plain track): every number and web address in
    it appears in the research, the registers or the intro's own sources; nothing private; no banned words; and the
    plain-words texts use none of the words the layman guide forbids ("simply", "just", "easy", praise);
  - the Romanian is checked for private data;
  - no picture carries PNG text chunks (a path or a user name could hide there);
  - the published copies are exactly what the source renders (a hand edit is caught).
"""
import re
import shutil
import struct
from pathlib import Path

import yaml

SRC = Path("docs") / "hidden-pages"
REGISTER = Path("decisions") / "ABOUT-PAGES.yaml"
DECISIONS = Path("decisions") / "PRODUCT-DECISIONS.yaml"
PUBLIC_DOC = Path("docs") / "HIDDEN-PAGES.md"
PUBLIC_SHOTS = Path("docs") / "screenshots" / "hidden-pages"
RO_DOC = SRC / "HIDDEN-PAGES.ro.md"
GENERATED = "<!-- generated by fieldkit build-harness hidden-pages-doc from the maintainer's source; edit the source -->"
LAYMAN_BANNED = re.compile(r"\b(simply|just|easy|easily|powerful|robust|seamless(ly)?)\b", re.I)
EN = {"removed": "Removed", "kept": "Kept", "changed": "Kept, changed", "network": "Talks to",
      "plain": "In plain words", "dev": "For developers", "table": ("Page", "What it is", "Talks to", "What we did"),
      "glance": "The pages at a glance", "gone": "Removed", "stay": "Kept", "no_shot": "No picture"}
RO = {"removed": "Eliminată", "kept": "Păstrată", "changed": "Păstrată, modificată", "network": "Vorbește cu",
      "plain": "Pe înțelesul tuturor", "table": ("Pagina", "Ce este", "Vorbește cu", "Ce am făcut"),
      "glance": "Paginile dintr-o privire", "gone": "Eliminate", "stay": "Păstrate", "no_shot": "Nicio imagine"}


class Refused(Exception):
    pass


def _yaml(p):
    return yaml.safe_load(Path(p).read_text(encoding="utf-8")) or {}


def register(owner):
    return {e["name"]: e for e in _yaml(Path(owner) / REGISTER).get("pages") or []}


def documented(reg):
    """The pages this document must explain: hidden now, or hidden before they were removed."""
    return {n for n, e in reg.items() if e.get("shown") == "hidden" or e.get("was") == "hidden"}


def load(owner):
    """-> (intro, {name: entry}); a page written twice is refused."""
    src = Path(owner) / SRC
    intro = _yaml(src / "intro.yaml") if (src / "intro.yaml").is_file() else {}
    entries = {}
    for f in sorted((src / "pages").glob("*.yaml")) if (src / "pages").is_dir() else []:
        for e in _yaml(f).get("pages") or []:
            if e.get("name") in entries:
                raise Refused(f"about:{e['name']} is written twice ({f.name})")
            entries[e.get("name")] = dict(e, _file=f.name)
    return intro, entries


def status(e, words):
    if e.get("verdict") == "remove":
        return f"{words['removed']} ({e['decision']})" if e.get("decision") else words["removed"]
    return f"{words['changed']} ({e['decision']})" if e.get("decision") else words["kept"]


def _one_line(s):
    return " ".join(str(s or "").split()).replace("|", "/")


def _section(name, entry, reg_e, words, lang, shots_rel):
    t = entry[lang]
    out = [f'<a id="about-{name}"></a>', "", f"### `about:{name}`: {t['title']}", ""]
    shots = entry.get("shots") or []
    for s in shots:
        out += [f"![about:{name}]({shots_rel}/{s})", ""]
    if not shots:
        out += [f"*{words['no_shot']}: {entry.get('no_shot')}*", ""]
    net = reg_e.get("network") if lang == "en" else t.get("network")
    out += [f"**{status(reg_e, words)}.** **{words['network']}:** {_one_line(net)}", ""]
    out += [f"#### {words['plain']}", "", t["layman"].strip(), ""]
    if lang == "en":
        out += [f"#### {words['dev']}", "", t["developer"].strip(), ""]
    out += ["---", ""]
    return out


def render(intro, entries, reg, lang):
    """-> markdown text of one language's document."""
    words = EN if lang == "en" else RO
    head = intro.get(lang) or {}
    order = intro.get("order") or sorted(entries)
    shots_rel = "screenshots/hidden-pages" if lang == "en" else "shots"
    out = [GENERATED, "", f"# {head.get('title', '')}", "", head.get("intro", "").strip(), ""]
    if lang == "en" and head.get("method"):
        out += [head["method"].strip(), ""]
    out += [f"## {words['glance']}", "", "| " + " | ".join(words["table"]) + " |", "|---|---|---|---|"]
    for n in order:
        e, r = entries[n], reg.get(n, {})
        net = r.get("network") if lang == "en" else e[lang].get("network")
        out.append(f"| [`about:{n}`](#about-{n}) | {_one_line(e[lang]['title'])} | {_one_line(net)} | {status(r, words)} |")
    out.append("")
    for group, want in ((words["gone"], "remove"), (words["stay"], "keep")):
        names = [n for n in order if reg.get(n, {}).get("verdict") == want]
        if not names:
            continue
        out += [f"## {group}", ""]
        for n in names:
            out += _section(n, entries[n], reg.get(n, {}), words, lang, shots_rel)
    return "\n".join(out).rstrip() + "\n"


def png_text_chunks(path):
    """-> chunk types that can carry text (tEXt, iTXt, zTXt) found in a PNG; [] when none."""
    data = Path(path).read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        return ["not a PNG"]
    found, i = [], 8
    while i + 8 <= len(data):
        n, kind = struct.unpack(">I4s", data[i:i + 8])
        if kind in (b"tEXt", b"iTXt", b"zTXt"):
            found.append(kind.decode())
        if kind == b"IEND":
            break
        i += 12 + n
    return found


def sources(owner):
    """The material every number and web address must come from."""
    o = Path(owner)
    extra = (_yaml(o / SRC / "intro.yaml").get("sources") or []) if (o / SRC / "intro.yaml").is_file() else []
    return [str(p) for p in sorted((o / SRC / "research").glob("*.md"))] + [str(o / REGISTER), str(o / DECISIONS)] + \
        [str(o / p) for p in extra]


def check(owner, patchset):
    """-> rows [{"check", "ok", "evidence"}]."""
    o, rows = Path(owner), []

    def row(check_, ok, ev):
        rows.append({"check": "hidden-pages doc: " + check_, "ok": bool(ok), "evidence": ev})
    reg = register(o)
    intro, entries = load(o)
    want = documented(reg)
    missing, extra = sorted(want - set(entries)), sorted(set(entries) - want)
    row("every page that is or was hidden is explained, and nothing else", not missing and not extra,
        "; ".join(filter(None, [("not explained: " + ", ".join("about:" + n for n in missing)) if missing else "",
                                ("not a hidden page: " + ", ".join("about:" + n for n in extra)) if extra else ""]))
        or f"{len(entries)} page(s) explained ({sum(1 for n in entries if reg.get(n, {}).get('verdict') == 'remove')} removed)")
    order = intro.get("order") or []
    dup = sorted({n for n in order if order.count(n) > 1})
    row("the order names every page once", set(order) == set(entries) and not dup,
        f"order {len(order)}, pages {len(entries)}" + (f"; twice: {dup}" if dup else "") +
        (f"; not in order: {sorted(set(entries) - set(order))}" if set(entries) - set(order) else "") +
        (f"; unknown in order: {sorted(set(order) - set(entries))}" if set(order) - set(entries) else ""))
    gaps, pics, chunks, banned = [], 0, [], []
    for n, e in sorted(entries.items()):
        for lang, keys in (("en", ("title", "layman", "developer")), ("ro", ("title", "network", "layman"))):
            gaps += [f"about:{n} {lang}.{k}" for k in keys if not str((e.get(lang) or {}).get(k) or "").strip()]
        if not e.get("shots") and not str(e.get("no_shot") or "").strip():
            gaps.append(f"about:{n} has no picture and no reason")
        for s in e.get("shots") or []:
            p = o / SRC / "shots" / s
            if not p.is_file():
                gaps.append(f"about:{n} picture {s} not found")
                continue
            pics += 1
            if png_text_chunks(p):
                chunks.append(f"{s}: {png_text_chunks(p)}")
        for m in LAYMAN_BANNED.finditer(str((e.get("en") or {}).get("layman") or "")):
            banned.append(f"about:{n}: '{m.group(0)}'")
    row("every entry has its texts and pictures", not gaps, "; ".join(gaps[:8]) + (f" (+{len(gaps) - 8})" if len(gaps) > 8 else "")
        if gaps else f"{len(entries)} entries complete, {pics} picture(s)")
    row("no picture carries text chunks (paths, user names)", not chunks, "; ".join(chunks[:5]) or f"{pics} picture(s) clean")
    row("the plain-words texts use none of the words the layman guide forbids", not banned,
        "; ".join(banned[:8]) or "none")
    if gaps or missing or extra:
        return rows
    pub, ro = Path(patchset) / PUBLIC_DOC, o / RO_DOC
    want_en, want_ro = render(intro, entries, reg, "en"), render(intro, entries, reg, "ro")
    for label, path, text in (("English (public)", pub, want_en), ("Romanian (private)", ro, want_ro)):
        have = path.read_text(encoding="utf-8") if path.is_file() else None
        row(f"the {label} copy is what the source renders", have == text,
            f"{path.name}: " + ("matches" if have == text else "missing" if have is None else "differs: run write=1"))
    from ..gdocs import releasedocs
    import tempfile
    tmp = Path(tempfile.mkdtemp(prefix="hidden_docs_"))
    (tmp / "HIDDEN-PAGES.md").write_text(want_en, encoding="utf-8")
    (tmp / "HIDDEN-PAGES.ro.md").write_text(want_ro, encoding="utf-8")
    r = releasedocs.check(sources=sources(o), plain=[str(tmp / "HIDDEN-PAGES.md")])
    f = [x for d in r["documents"].values() for x in d["findings"]] + r["problems"]
    row("the English holds to its sources (numbers, web addresses), keeps nothing private, no banned words", r["ok"],
        "; ".join(f[:6]) + (f" (+{len(f) - 6})" if len(f) > 6 else "") if f else
        f"{r['sources']} source file(s); every number and web address found")
    from ..gdocs import checks
    pf = checks.privacy_findings(want_ro, corpus="")
    row("the Romanian keeps nothing private", not pf, "; ".join(pf[:6]) or "clean")
    shutil.rmtree(tmp, ignore_errors=True)
    return rows


def write(owner, patchset, say=print):
    """Render both documents and publish the pictures they use into the patch-set repo (locally; never pushed)
    -> {"written": [paths], "rows": check rows}."""
    o, ps = Path(owner), Path(patchset)
    reg = register(o)
    intro, entries = load(o)
    en, ro = render(intro, entries, reg, "en"), render(intro, entries, reg, "ro")
    out = []
    (ps / PUBLIC_DOC).parent.mkdir(parents=True, exist_ok=True)
    (ps / PUBLIC_DOC).write_bytes(en.encode("utf-8"))
    (o / RO_DOC).write_bytes(ro.encode("utf-8"))
    out += [str(ps / PUBLIC_DOC), str(o / RO_DOC)]
    shots = ps / PUBLIC_SHOTS
    shots.mkdir(parents=True, exist_ok=True)
    used = {s for e in entries.values() for s in e.get("shots") or []}
    for s in sorted(used):
        src = o / SRC / "shots" / s
        if src.is_file() and (not (shots / s).is_file() or (shots / s).read_bytes() != src.read_bytes()):
            shutil.copyfile(src, shots / s)
            out.append(str(shots / s))
    for stale in sorted(shots.glob("*.png")):          # this folder is the tool's own: a picture no page uses goes
        if stale.name not in used:
            stale.unlink()
            out.append(f"removed {stale}")
    say(f"  wrote {len(out)} file(s)")
    return {"written": out, "rows": check(o, ps)}
