"""T-157-34-A (2026-10-07): a generated upstream file (DO NOT EDIT) may differ from pristine only by a trailing
/* GORILLA block. The 157 design-token files were 155-era copies for five builds and no text check noticed."""
import subprocess

from fieldkit.buildh import techniques

GEN = b"/* DO NOT EDIT this file directly, instead modify the relevant *.tokens.json file */\n:root {\n  --a: 1;\n}\n"


def _repo(tmp_path):
    w = tmp_path / "tree"
    (w / "dist").mkdir(parents=True)
    (w / "dist" / "tokens.css").write_bytes(GEN)
    (w / "dist" / "plain.css").write_bytes(b":root { --b: 2; }\n")
    g = lambda *a: subprocess.run(["git", "-c", "core.autocrlf=false", "-C", str(w), *a], check=True, capture_output=True)
    g("init", "-q")
    g("add", ".")
    g("-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-m", "pristine")
    return w, g


def _commit(w, g, data, plain=None):
    (w / "dist" / "tokens.css").write_bytes(data)
    if plain:
        (w / "dist" / "plain.css").write_bytes(plain)
    g("-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-am", "change")


def test_an_appended_gorilla_block_holds(tmp_path):
    w, g = _repo(tmp_path)
    _commit(w, g, GEN + b"\n/* GORILLA: black */\n:root { --a: 0; }\n", plain=b":root { --b: 3; }\n")
    assert techniques._append_only(w, "DO NOT EDIT") == ([], 1)          # plain.css is not generated: free to edit


def test_an_in_place_edit_or_an_older_copy_fails(tmp_path):
    w, g = _repo(tmp_path)
    _commit(w, g, GEN.replace(b"--a: 1;", b"--a: 2;"))
    bad, checked = techniques._append_only(w, "DO NOT EDIT")
    assert checked == 1 and bad[0][0] == "dist/tokens.css" and "restore it from pristine" in bad[0][1]


def test_an_unmarked_tail_fails(tmp_path):
    w, g = _repo(tmp_path)
    _commit(w, g, GEN + b":root { --a: 0; }\n")
    bad, _ = techniques._append_only(w, "DO NOT EDIT")
    assert bad and "/* GORILLA" in bad[0][1]


def test_the_technique_is_in_the_gate():
    t = next(x for x in techniques.TECHNIQUES if x["id"] == "T-157-34-A")
    assert t["signals"] == [{"name": "generated-files-append-only", "kind": "append_only", "header": "DO NOT EDIT"}]
