"""readiness - how much of the collection an agent can rely on, measured, never typed.

    fieldkit readiness [--json]              counts per trust level, per source, top blockers
    fieldkit readiness --write-docs          refresh local/READINESS.md

The block between the READINESS markers is written by this module, so the
numbers can never drift from the scan (the 216 vs 479 mismatch of 2026-09-29
came from typing counts by hand). It describes YOUR machine, private tools
included, so it lives in local/ (git-ignored), not in the published README.
"""
import collections
import re

from ..core import settings
from . import cards as cardmod

DOCS = settings.ROOT / "local" / "READINESS.md"
BEGIN, END = "<!-- READINESS:BEGIN (generated by fieldkit readiness --write-docs) -->", "<!-- READINESS:END -->"


def report(cards=None):
    cards = cardmod.all_cards() if cards is None else cards
    results = cardmod.test_results()
    levels = collections.Counter()
    by_source = collections.defaultdict(collections.Counter)
    blockers = collections.Counter()
    rows = []
    for c in cards:
        if c.get("retired"):
            continue
        lvl, why = cardmod.trust(c, results)
        levels[lvl] += 1
        src = "registered" if not c.get("draft") else c["id"].split("/")[0]
        by_source[src][lvl] += 1
        for w in why:
            blockers[re.sub(r"\(.*?\)", "", w).strip()] += 1
        rows.append({"id": c["id"], "level": lvl, "why": why, "draft": c.get("draft", False)})
    py = [c for c in cards if str(c.get("path", "")).endswith(".py") and c.get("draft")]
    return {
        "total": sum(levels.values()),
        "levels": {lv: levels.get(lv, 0) for lv in cardmod.LEVELS},
        "registered": sum(1 for c in cards if not c.get("draft") and not c.get("retired")),
        "registered_without_test": sum(1 for c in cards if not c.get("draft") and not c.get("retired")
                                       and not c.get("tests") and c.get("path")),
        "gathered_python": len(py),
        "gathered_not_probe_safe": sum(1 for c in py if c.get("probe") != "safe"),
        "hard_coded_home_files": sum(1 for c in cards if c.get("portable") is False),
        "by_source": {k: dict(v) for k, v in sorted(by_source.items())},
        "top_blockers": blockers.most_common(10),
        "rows": rows,
    }


def lines(r):
    L = r["levels"]
    out = [f"{r['total']} tools: {L['verified']} verified, {L['tested']} tested, {L['carded']} carded, "
           f"{L['gathered']} gathered only.",
           f"registered {r['registered']} ({r['registered_without_test']} without a test); gathered Python "
           f"{r['gathered_python']} ({r['gathered_not_probe_safe']} not safe to start blind); "
           f"{r['hard_coded_home_files']} files hard-code a home path.",
           "top blockers:"]
    out += [f"  {n:>4}  {w}" for w, n in r["top_blockers"]]
    return out


def docs_block(r):
    L = r["levels"]
    body = ["| Trust level | Tools | Meaning |", "|---|---|---|",
            f"| verified | {L['verified']} | tested, portable, safe to start, and changes have preview/undo/verify |",
            f"| tested | {L['tested']} | reviewed card and passing tests, but a blocker remains |",
            f"| carded | {L['carded']} | reviewed card (inputs, safety known), tests missing or not passed |",
            f"| gathered | {L['gathered']} | in the toolbox; draft card only - an agent must not run it unreviewed |",
            "",
            f"{r['total']} tools in all. Registered: {r['registered']} ({r['registered_without_test']} without a test). "
            f"Gathered Python scripts: {r['gathered_python']}, of which {r['gathered_not_probe_safe']} are not safe to "
            f"start blind (library modules, scripts that run on load, scripts without a command line). "
            f"{r['hard_coded_home_files']} files hard-code a home folder.",
            "", "Top blockers:", ""]
    body += [f"- {w}: {n}" for w, n in r["top_blockers"]]
    return "\n".join([BEGIN] + body + [END])


def write_docs(r=None):
    r = r or report()
    DOCS.parent.mkdir(parents=True, exist_ok=True)
    text = DOCS.read_text(encoding="utf-8") if DOCS.is_file() else "# Readiness of this machine's tools\n"
    block = docs_block(r)
    if BEGIN in text and END in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda m: block, text, flags=re.S)
    else:
        text = text.rstrip() + "\n\n## Readiness (generated)\n\n" + block + "\n"
    DOCS.write_text(text, encoding="utf-8", newline="\n")
    return r
