"""The local servers: a TLS origin (HTTP/1.1 and HTTP/2), the report host, an HTTP/3 server for B3, and a plain
calibration server; all on 127.0.0.1, all in one background event loop (Lab), together with the relay.

Every request is logged with its protocol, path, body bytes in and out, and the time it arrived (the origin sits at
the far end of the emulated link). The report host is reached through the relay WITHOUT shaping: it is the
benches' control channel, so a page's "loaded" message reaches the harness at once, timed at the browser's side.

The event loop uses a high-resolution clock (time.perf_counter) and, on Windows, asks for a 1 ms timer resolution
for this process only (timeBeginPeriod), so a 10 ms one-way delay is 10 ms and not one 15.6 ms timer tick.
"""
import asyncio
import json
import ssl
import sys
import threading
import time
from dataclasses import dataclass, field
from urllib.parse import parse_qs, urlsplit

import h2.config
import h2.connection
import h2.events
import h2.exceptions
import h2.settings

from . import fixtures

IDLE = 300                       # seconds an idle server connection is kept (B5 idles 90 s)
H2_WINDOW = 16 * 1024 * 1024     # generous: the server must never be the bottleneck
clock = time.perf_counter


@dataclass
class Req:
    role: str
    proto: str
    method: str
    target: str
    headers: dict
    t_arrive: float
    conn: int
    body_len: int = 0
    t_body_first: float = None
    t_body_last: float = None
    body_text: str = ""

    @property
    def path(self):
        return urlsplit(self.target).path

    @property
    def query(self):
        return {k: v[0] for k, v in parse_qs(urlsplit(self.target).query).items()}


@dataclass
class Resp:
    status: int = 200
    headers: list = field(default_factory=list)
    body: bytes = b""
    blob: int = 0                 # > 0: send this many generated bytes instead of `body`
    pace: float = 0.0             # > 0: seconds between chunks (a slow, long-lived response)

    def length(self):
        return self.blob if self.blob else len(self.body)

    def chunks(self):
        if self.pace:
            for i in range(0, len(self.body)):
                yield self.body[i:i + 1]
            return
        if self.blob:
            yield from fixtures.blob_chunks(self.blob)
        elif self.body:
            for i in range(0, len(self.body), 65536):
                yield self.body[i:i + 65536]


@dataclass
class RunState:
    rid: str
    steps: list                   # [(step name, url)]
    marks: list = field(default_factory=list)
    done: threading.Event = field(default_factory=threading.Event)
    final: dict = None            # counters after the last step and the grace period (set by the harness)

    def mark(self, step, ev):
        for m in self.marks:
            if m["step"] == step and m["ev"] == ev:
                return m
        return None


class Origin:
    """Fixture site, blobs, upload sink and the report host's control endpoints."""

    def __init__(self, files):
        self.files = files
        self.requests = []
        self.runs = {}
        self.snapshot = lambda: {}
        self._conn = 0
        self.h3_port = None
        self.lock = threading.Lock()

    def conn_id(self):
        self._conn += 1
        return self._conn

    def new_run(self, rid, steps):
        st = RunState(rid, list(steps))
        with self.lock:
            self.runs[rid] = st
        return st

    def log(self, req, resp, sent, t_end):
        self.requests.append({"role": req.role, "proto": req.proto, "method": req.method, "path": req.path,
                              "target": req.target, "status": resp.status, "req_body": req.body_len, "resp_body": sent,
                              "t_arrive": req.t_arrive, "t_end": t_end, "conn": req.conn})

    # --- the application -------------------------------------------------------------------------------------
    def app(self, req):
        if req.role == "report":
            return self.report(req)
        p = req.path
        if p.startswith("/blob/"):
            try:
                n = int(p.split("/")[2])
            except ValueError:
                return Resp(404, [("content-type", "text/plain")], b"no")
            return Resp(200, [("content-type", "application/octet-stream"), ("cache-control", "no-store")], blob=n)
        if p.startswith("/trickle/"):                     # one byte per second for N seconds (B5's busy connection)
            try:
                n = max(1, min(600, int(p.split("/")[2])))
            except ValueError:
                return Resp(404, [("content-type", "text/plain")], b"no")
            return Resp(200, [("content-type", "text/plain"), ("cache-control", "no-store"),
                              ("access-control-allow-origin", "*")], b"." * n, pace=1.0)
        if p == "/sink":
            dt = (req.t_body_last - req.t_body_first) if req.t_body_first is not None else None
            out = {"bytes": req.body_len, "origin_seconds": dt,
                   "origin_mbps": (req.body_len * 8 / dt / 1e6) if dt and dt > 0 else None}
            return Resp(200, [("content-type", "application/json"), ("cache-control", "no-store")],
                        json.dumps(out).encode())
        f = self.files.get(p)
        if not f:
            return Resp(404, [("content-type", "text/plain"), ("cache-control", "no-store")], b"not here\n")
        h = [("content-type", f["type"])]
        body = f["body"]
        if f["gzip"] and "gzip" in req.headers.get("accept-encoding", ""):
            body = f["gzip"]
            h += [("content-encoding", "gzip"), ("vary", "Accept-Encoding")]
        h.append(("cache-control", "public, max-age=86400" if f["cache"] else "private, max-age=0, must-revalidate"))
        if req.role == "h3tcp":
            h.append(("alt-svc", f'h3=":{self.h3_port}"; ma=3600'))
        return Resp(200, h, body)

    def report(self, req):
        q, p = req.query, req.path
        cors = [("access-control-allow-origin", "*"), ("cache-control", "no-store")]
        st = self.runs.get(q.get("run", ""))
        if p == "/go" and st:
            url = dict(st.steps).get(q.get("step"))
            wait = max(0, min(60, int(q.get("wait", "0") or 0)))     # let start-up work settle before the clock starts
            js = ("setTimeout(function(){ NB.mark('start').then(function(){ location.replace(%s); }); }, %d);"
                  % (json.dumps(url), wait * 1000))
            return Resp(200, [("content-type", "text/html; charset=utf-8")] + cors, fixtures.page("go", "", js))
        if p == "/mark" and st:
            try:
                data = json.loads(req.body_text or "{}")
            except (ValueError, AttributeError):
                data = {}
            st.marks.append({"step": q.get("step"), "ev": q.get("ev"), "t": req.t_arrive, "data": data,
                             "snap": self.snapshot()})
            return Resp(200, [("content-type", "text/plain")] + cors, b"ok")
        if p == "/next" and st:
            names = [s for s, _ in st.steps]
            i = names.index(q.get("step")) if q.get("step") in names else len(names)
            if i + 1 < len(names):
                body = {"step": names[i + 1], "url": st.steps[i + 1][1]}
            else:
                body = {}
                st.done.set()
            return Resp(200, [("content-type", "application/json")] + cors, json.dumps(body).encode())
        return Resp(404, [("content-type", "text/plain")] + cors, b"no run\n")

    # --- HTTP/1.1 ----------------------------------------------------------------------------------------------
    async def serve_h1(self, role, reader, writer, cid):
        while True:
            try:
                head = await asyncio.wait_for(reader.readuntil(b"\r\n\r\n"), IDLE)
            except (asyncio.IncompleteReadError, asyncio.TimeoutError, asyncio.LimitOverrunError, ConnectionError, OSError):
                break
            t = clock()
            lines = head.decode("latin-1").split("\r\n")
            try:
                method, target, _ = lines[0].split(" ", 2)
            except ValueError:
                break
            hdr = {}
            for ln in lines[1:]:
                if ":" in ln:
                    k, v = ln.split(":", 1)
                    hdr[k.strip().lower()] = v.strip()
            req = Req(role, "http/1.1", method, target, hdr, t, cid)
            body = bytearray() if role == "report" else None
            try:
                if "content-length" in hdr:
                    left = int(hdr["content-length"])
                    while left > 0:
                        b = await reader.read(min(65536, left))
                        if not b:
                            raise ConnectionError("body cut short")
                        self._body(req, b, body)
                        left -= len(b)
                elif "chunked" in hdr.get("transfer-encoding", "").lower():
                    while True:
                        size = int((await reader.readuntil(b"\r\n")).split(b";")[0].strip(), 16)
                        if size == 0:
                            await reader.readuntil(b"\r\n")
                            break
                        b = await reader.readexactly(size)
                        self._body(req, b, body)
                        await reader.readexactly(2)
            except (asyncio.IncompleteReadError, ConnectionError, ValueError, OSError):
                break
            req.body_text = bytes(body).decode("utf-8", "replace") if body is not None else ""
            resp = self.app(req)
            out = [f"HTTP/1.1 {resp.status} X"] + [f"{k}: {v}" for k, v in resp.headers] + [
                f"content-length: {resp.length()}", "connection: keep-alive", f"keep-alive: timeout={IDLE}"]
            sent = 0
            try:
                writer.write(("\r\n".join(out) + "\r\n\r\n").encode("latin-1"))
                for c in resp.chunks():
                    if resp.pace and sent:
                        await asyncio.sleep(resp.pace)
                    writer.write(c)
                    sent += len(c)
                    await writer.drain()
                await writer.drain()
            except (ConnectionError, OSError):
                self.log(req, resp, sent, clock())
                break
            self.log(req, resp, sent, clock())
            if hdr.get("connection", "").lower() == "close":
                break
        writer.close()

    @staticmethod
    def _body(req, b, keep):
        now = clock()
        if req.t_body_first is None:
            req.t_body_first = now
        req.t_body_last = now
        req.body_len += len(b)
        if keep is not None and len(keep) < 65536:
            keep.extend(b)

    # --- HTTP/2 ------------------------------------------------------------------------------------------------
    async def serve_h2(self, role, reader, writer, cid):
        conn = h2.connection.H2Connection(h2.config.H2Configuration(client_side=False, header_encoding="utf-8"))
        conn.initiate_connection()
        conn.update_settings({h2.settings.SettingCodes.INITIAL_WINDOW_SIZE: H2_WINDOW,
                              h2.settings.SettingCodes.MAX_CONCURRENT_STREAMS: 256})
        conn.increment_flow_control_window(H2_WINDOW - 65535)
        writer.write(conn.data_to_send())
        streams, tasks, wev = {}, set(), asyncio.Event()
        while True:
            try:
                data = await asyncio.wait_for(reader.read(262144), IDLE)
            except (asyncio.TimeoutError, ConnectionError, OSError):
                break
            if not data:
                break
            try:
                events = conn.receive_data(data)
            except h2.exceptions.ProtocolError:
                break
            stop = False
            for ev in events:
                if isinstance(ev, h2.events.RequestReceived):
                    hd = dict(ev.headers)
                    req = Req(role, "h2", hd.get(":method", "GET"), hd.get(":path", "/"),
                              {k.lower(): v for k, v in hd.items() if not k.startswith(":")}, clock(), cid)
                    req.body_text = ""
                    streams[ev.stream_id] = (req, bytearray() if role == "report" else None)
                    if ev.stream_ended:
                        tasks.add(asyncio.ensure_future(self._h2_respond(conn, writer, ev.stream_id, streams.pop(ev.stream_id), wev)))
                elif isinstance(ev, h2.events.DataReceived):
                    if ev.stream_id in streams:
                        req, keep = streams[ev.stream_id]
                        self._body(req, ev.data, keep)
                    conn.acknowledge_received_data(ev.flow_controlled_length, ev.stream_id)
                elif isinstance(ev, h2.events.StreamEnded):
                    if ev.stream_id in streams:
                        tasks.add(asyncio.ensure_future(self._h2_respond(conn, writer, ev.stream_id, streams.pop(ev.stream_id), wev)))
                elif isinstance(ev, (h2.events.WindowUpdated, h2.events.RemoteSettingsChanged)):
                    wev.set()
                elif isinstance(ev, h2.events.StreamReset):
                    streams.pop(ev.stream_id, None)
                    wev.set()
                elif isinstance(ev, h2.events.ConnectionTerminated):
                    stop = True
            try:
                writer.write(conn.data_to_send())
                await writer.drain()
            except (ConnectionError, OSError):
                break
            tasks = {t for t in tasks if not t.done()}
            if stop:
                break
        for t in tasks:
            t.cancel()
        writer.close()

    async def _h2_respond(self, conn, writer, sid, pair, wev):
        req, keep = pair
        req.body_text = bytes(keep).decode("utf-8", "replace") if keep is not None else ""
        resp = self.app(req)
        hdr = [(":status", str(resp.status))] + [(k.lower(), str(v)) for k, v in resp.headers] + [
            ("content-length", str(resp.length()))]
        sent = 0
        try:
            conn.send_headers(sid, hdr, end_stream=resp.length() == 0)
            writer.write(conn.data_to_send())
            for c in resp.chunks():
                if resp.pace and sent:
                    await asyncio.sleep(resp.pace)
                view = memoryview(c)
                while len(view):
                    while conn.local_flow_control_window(sid) <= 0:
                        wev.clear()
                        await wev.wait()
                    n = min(len(view), conn.local_flow_control_window(sid), conn.max_outbound_frame_size)
                    conn.send_data(sid, bytes(view[:n]))
                    view = view[n:]
                    sent += n
                    writer.write(conn.data_to_send())
                    await writer.drain()
            if resp.length():
                conn.end_stream(sid)
                writer.write(conn.data_to_send())
        except (h2.exceptions.StreamClosedError, h2.exceptions.ProtocolError, KeyError, ConnectionError, OSError):
            pass
        self.log(req, resp, sent, clock())

    # --- the TLS front door -------------------------------------------------------------------------------------
    def tls_handler(self, role):
        async def handle(reader, writer):
            cid = self.conn_id()
            sslobj = writer.get_extra_info("ssl_object")
            alpn = sslobj.selected_alpn_protocol() if sslobj else None
            try:
                if alpn == "h2":
                    await self.serve_h2(role, reader, writer, cid)
                else:
                    await self.serve_h1(role, reader, writer, cid)
            except Exception:                       # one broken connection never stops the server
                writer.close()
        return handle

    async def calib(self, reader, writer):
        """Plain TCP calibration peer: PING -> PONG, DOWN n -> n bytes, UP n + n bytes -> OK."""
        try:
            while True:
                line = await reader.readline()
                if not line:
                    break
                cmd = line.decode().split()
                if cmd[0] == "PING":
                    writer.write(b"PONG\n")
                elif cmd[0] == "DOWN":
                    for c in fixtures.blob_chunks(int(cmd[1])):
                        writer.write(c)
                        await writer.drain()
                elif cmd[0] == "UP":
                    await reader.readexactly(int(cmd[1]))
                    writer.write(b"OK\n")
                await writer.drain()
        except (ConnectionError, asyncio.IncompleteReadError, OSError, IndexError, ValueError):
            pass
        writer.close()


def tls_context(cert, key, alpn):
    ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    ctx.load_cert_chain(str(cert), str(key))
    ctx.set_alpn_protocols(list(alpn))
    return ctx


def _h3_protocol(origin):
    from aioquic.asyncio import QuicConnectionProtocol
    from aioquic.h3.connection import H3_ALPN, H3Connection
    from aioquic.h3.events import HeadersReceived
    from aioquic.quic.events import ProtocolNegotiated

    class H3(QuicConnectionProtocol):
        def __init__(self, *a, **k):
            super().__init__(*a, **k)
            self.h3 = None
            self.cid = origin.conn_id()

        def quic_event_received(self, event):
            if isinstance(event, ProtocolNegotiated) and event.alpn_protocol in H3_ALPN:
                self.h3 = H3Connection(self._quic)
            if self.h3 is None:
                return
            for ev in self.h3.handle_event(event):
                if isinstance(ev, HeadersReceived):
                    hd = {k.decode(): v.decode() for k, v in ev.headers}
                    req = Req("h3", "h3", hd.get(":method", "GET"), hd.get(":path", "/"), hd, clock(), self.cid)
                    req.body_text = ""
                    resp = origin.app(req)
                    body = b"".join(resp.chunks())
                    self.h3.send_headers(ev.stream_id, [(b":status", str(resp.status).encode())] + [
                        (k.encode(), str(v).encode()) for k, v in resp.headers] + [(b"content-length", str(len(body)).encode())])
                    self.h3.send_data(ev.stream_id, body, end_stream=True)
                    self.transmit()
                    origin.log(req, resp, len(body), clock())
    return H3, H3_ALPN


class _PreciseLoop(asyncio.ProactorEventLoop if sys.platform == "win32" else asyncio.SelectorEventLoop):
    def __init__(self):
        super().__init__()
        self._clock_resolution = 1e-6

    def time(self):
        return time.perf_counter()


class Lab:
    """All local servers and the relay in one background thread. Ports are chosen by the system (127.0.0.1:0)."""

    def __init__(self, files, certs, relay, want_h3=False):
        self.origin = Origin(files)
        self.certs = certs
        self.relay = relay
        self.want_h3 = want_h3
        self.ports = {}
        self.loop = None
        self.thread = None
        self._servers = []
        self._quic = None
        self.h3_error = None
        self._winmm = None

    def start(self):
        ready = threading.Event()
        err = []

        def main():
            if sys.platform == "win32":
                try:
                    import ctypes
                    self._winmm = ctypes.WinDLL("winmm")
                    self._winmm.timeBeginPeriod(1)
                except OSError:
                    self._winmm = None
            self.loop = _PreciseLoop()
            asyncio.set_event_loop(self.loop)
            try:
                self.loop.run_until_complete(self._start())
            except Exception as e:                 # noqa: BLE001 - reported to the caller
                err.append(e)
                ready.set()
                return
            ready.set()
            self.loop.run_forever()
        self.thread = threading.Thread(target=main, name="netbench-lab", daemon=True)
        self.thread.start()
        ready.wait(60)
        if err:
            raise RuntimeError(f"local servers did not start: {err[0]}")
        return self

    async def _start(self):
        o, c = self.origin, self.certs
        both = tls_context(c["cert"], c["key"], ("h2", "http/1.1"))
        only1 = tls_context(c["cert"], c["key"], ("http/1.1",))
        for role, ctx in (("www", both), ("h1", only1), ("report", both)):
            s = await asyncio.start_server(o.tls_handler(role), "127.0.0.1", 0, ssl=ctx, backlog=256)
            self._servers.append(s)
            self.ports[role] = s.sockets[0].getsockname()[1]
        s = await asyncio.start_server(o.calib, "127.0.0.1", 0)
        self._servers.append(s)
        self.ports["calib"] = s.sockets[0].getsockname()[1]
        if self.want_h3:
            await self._start_h3(both)
        o.snapshot = self.snapshot
        self.relay.routes = {
            "www.netbench.test": (self.ports["www"], True),
            "h1.netbench.test": (self.ports["h1"], True),
            "h1b.netbench.test": (self.ports["h1"], True),          # B5's busy connection, kept apart from h1's pool
            "calib.netbench.test": (self.ports["calib"], True),
            "report.netbench.test": (self.ports["report"], False),
        }
        s = await asyncio.start_server(self.relay.handle, "127.0.0.1", 0, backlog=256)
        self._servers.append(s)
        self.ports["relay"] = s.sockets[0].getsockname()[1]

    async def _start_h3(self, ctx):
        """TCP origin and QUIC server on the same port number (Alt-Svc h3=":port")."""
        from aioquic.asyncio import serve
        from aioquic.quic.configuration import QuicConfiguration
        last = None
        for _ in range(20):
            s = await asyncio.start_server(self.origin.tls_handler("h3tcp"), "127.0.0.1", 0, ssl=ctx)
            port = s.sockets[0].getsockname()[1]
            try:
                proto, alpn = _h3_protocol(self.origin)
                cfg = QuicConfiguration(is_client=False, alpn_protocols=alpn)
                cfg.load_cert_chain(str(self.certs["cert"]), str(self.certs["key"]))
                self._quic = await serve("127.0.0.1", port, configuration=cfg, create_protocol=proto)
            except OSError as e:
                last = e
                s.close()
                continue
            except Exception as e:                    # noqa: BLE001 - B3 reports it as UNMEASURED
                self.h3_error = f"{type(e).__name__}: {e}"
                s.close()
                return
            self._servers.append(s)
            self.ports["h3"] = port
            self.origin.h3_port = port
            return
        self.h3_error = f"no port free for both TCP and UDP: {last}"

    def call(self, coro, timeout=None):
        return asyncio.run_coroutine_threadsafe(coro, self.loop).result(timeout)

    def snapshot(self):
        """Counters at this instant (called inside the loop when a mark arrives)."""
        return {"relay": self.relay.totals(), "requests": len(self.origin.requests)}

    def snap(self):
        """snapshot() taken inside the loop thread, from any thread."""
        async def _s():
            return self.snapshot()
        return self.call(_s(), 30)

    def stop(self):
        if not self.loop:
            return

        async def _close():
            for s in self._servers:
                s.close()
            if self._quic is not None:
                self._quic.close()
            self.relay.close_all()
            me = asyncio.current_task()
            rest = [t for t in asyncio.all_tasks() if t is not me]
            for t in rest:
                t.cancel()
            await asyncio.gather(*rest, return_exceptions=True)
        try:
            self.call(_close(), 15)
        except Exception:                             # noqa: BLE001 - stopping must not raise
            pass
        self.loop.call_soon_threadsafe(self.loop.stop)
        self.thread.join(15)
        if self._winmm is not None:
            self._winmm.timeEndPeriod(1)
